import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <form target="_blank" method="post" className={styles.form}>
            <img src="/imagem/madamepet.jpg" alt="" />
            <input type="email" name="email" placeholder="E-Mail"/>
            <input type="password" name="password" placeholder="Senha"/>
            <input type="submit" value="Entrar"/>
          </form>
          <div className={styles.criarConta}>
            <b><p>Ainda Não tem conta? <a href="">Inscreva-se</a></p></b>
          </div>
        </div>
      </main>
    </>
  )
}
